apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  credentials:
    source: Secret
    secretRef:
      name: localstack-aws-secret
      namespace: crossplane-system
      key: creds
  endpoint:
    hostnameImmutable: true
    url:
      type: Static
      static: http://localstack.localstack.svc.cluster.local:4566
